' Gambas module file

'
' ebook-optimizer
' Book optimization
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

Export

'' Return the same image but with a frame

Public Function ImageFrame(img As Image, cColors As Collection) As Image

  Dim lt As Variant
  'Dim img As Image

  For Each lt In cColors

    Paint.Begin(img)
    Paint.NewPath
    Paint.Brush = Paint.Color(Color.Black)

    Paint.LineWidth = 3
    Paint.MoveTo(2, 2)

    Paint.LineTo(img.W - 2, 2)
    Paint.LineTo(img.W - 2, img.H - 2)
    Paint.LineTo(2, img.H - 2)
    Paint.LineTo(2, 2)

    Paint.Stroke
    Paint.End
  Next
  Return img

End
